### ISSUE TITLE
TO location is always created as a folder

### ISSUE THREAD

**Issue by SuzannePHSA** [webextensions/copy-files-from-to#24] opened 2023-11-21 03:34 UTC
Running 3.8.0
I'm seeing that the "to" location is always created as a folder, rather than a file. This is the `package.json`:

```
 "copyFiles": [
    {
      "//": "--- Alpine ---",
      "from": "../../../../node_modules/alpinejs/dist/cdn.min.js",
      "to": "dist/js/alpine.min.js"
    },
    {
      "//": "--- Focus plugin for Alpine ---",
      "from": "../../../../node_modules/@alpinejs/focus/dist/cdn.min.js",
      "to": "dist/js/alpine-focus.min.js"
    }
```

This results in a folder called `dist/js/alpine.min.js` containing a file called `cdn.min.js`. If I rename the `to` location to have the same name as the `from` folder, the results are the same.

![image](https://github.com/webextensions/copy-files-from-to/assets/150383570/6cb154e2-c148-4535-bf7b-e8214fddd25a)

**Comment by webextensions** [comment] 2023-11-22 19:28
@SuzannePHSA 
Based on the provided information, the issue couldn't be reproduced and it seemed to work fine.

Can you try using the latest version of copy-files-from-to (v3.9.1) and provide the following information:
* The value provided for `"copyFilesSettings"` property, if it is not set, then mention that.
* Run the command with the `--verbose` option, like `$ copy-files-from-to --verbose` and share the output

**Comment by webextensions** [comment] 2023-12-15 19:10
Closing the issue due to lack of steps to reproduce.

**Closed by webextensions** 2023-12-15 19:10 UTC
